
LIBNAME GES2012 'R:\FILES\GES12';

options nofmterr; run;

PROC EXPORT DATA= GES2012.ACCIDENT 
            OUTFILE= "R:\FILES\GES12\FlatFile\ACCIDENT.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.vehicle 
            OUTFILE= "R:\FILES\GES12\FlatFile\VEHICLE.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.parkwork 
            OUTFILE= "R:\FILES\GES12\FlatFile\PARKWORK.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.person 
            OUTFILE= "R:\FILES\GES12\FlatFile\PERSON.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.cevent
            OUTFILE= "R:\FILES\GES12\FlatFile\CEVENT.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.vevent
            OUTFILE= "R:\FILES\GES12\FlatFile\VEVENT.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.Vsoe 
            OUTFILE= "R:\FILES\GES12\FlatFile\VSOE.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.distract
            OUTFILE= "R:\FILES\GES12\FlatFile\DISTRACT.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.factor
            OUTFILE= "R:\FILES\GES12\FlatFile\FACTOR.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.safetyeq 
            OUTFILE= "R:\FILES\GES12\FlatFile\SAFETYEQ.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.drimpair
            OUTFILE= "R:\FILES\GES12\FlatFile\DRIMPAIR.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.nmimpair
            OUTFILE= "R:\FILES\GES12\FlatFile\NMIMPAIR.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.nmcrash
            OUTFILE= "R:\FILES\GES12\FlatFile\NMCRASH.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.nmprior
            OUTFILE= "R:\FILES\GES12\FlatFile\NMPRIOR.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.maneuver
            OUTFILE= "R:\FILES\GES12\FlatFile\MANEUVER.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.violatn
            OUTFILE= "R:\FILES\GES12\FlatFile\VIOLATN.TXT" 
            DBMS=TAB REPLACE;
RUN;

PROC EXPORT DATA= GES2012.vision
            OUTFILE= "R:\FILES\GES12\FlatFile\VISION.TXT" 
            DBMS=TAB REPLACE;
RUN;

/*PROC EXPORT DATA=GES2012.pbtype
            OUTFILE = "R:\FILES\GES12\FlatFile\PBTYPE.TXT" 
 			DBMS=TAB REPLACE;
*/

PROC EXPORT DATA= GES2012.damage
            OUTFILE= "R:\FILES\GES12\FlatFile\DAMAGE.TXT" 
            DBMS=TAB REPLACE;
/*added in 2012*/

RUN;
